apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: create-file-run-
spec:
  pipelineRef:
    name: create-file
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    persistentVolumeClaim:
      claimName: tekton-pvc